version: '3.8'

services:
  stockgame-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      # 서버 설정
      NODE_ENV: production
      PORT: 3000

      # JWT 설정 (실제 배포시 변경 필요)
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-here}
      JWT_ACCESS_EXPIRES_IN: ${JWT_ACCESS_EXPIRES_IN:-2h}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}

      # OAuth 설정 (실제 값으로 변경 필요)
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI:-http://localhost:3000/api/auth/kakao/callback}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI:-http://localhost:3000/api/auth/google/callback}

      # URL 설정
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
      BACKEND_URL: ${BACKEND_URL:-http://localhost:3000}

    volumes:
      # SQLite 데이터베이스 영구 저장
      - ./data:/app/data
      - ./stockgame.db:/app/stockgame.db

    restart: unless-stopped

    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000/api',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# 볼륨 정의
volumes:
  stockgame_data:
    driver: local
