name: Deploy Frontend to GitHub Pages

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Check if frontend files changed
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          stockGame-fe/**
          .github/workflows/deploy-frontend.yml
    
    - name: Skip deployment if no frontend changes
      if: steps.changed-files.outputs.any_changed != 'true'
      run: |
        echo "No frontend files changed, skipping deployment"
        exit 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './stockGame-fe/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd stockGame-fe
        npm ci
    
    - name: Build
      run: |
        cd stockGame-fe
        npm run build
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        VITE_KAKAO_CLIENT_ID: ${{ secrets.VITE_KAKAO_CLIENT_ID }}
        VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './stockGame-fe/dist'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4